git:
  depth: 200

language: cpp

script: cmake

compiler:
  - gcc
  # - clang

os: 
  - linux
  - osx

env:
  global:
  - CXXSTD=''
  - CXXSTD='cxxflags="-std=c++11"'
  - GCC_VERSION="4.9"
  matrix:
    - BUILD_TYPE=Debug
    # - BUILD_TYPE=Release


matrix:
  # For now disable gcc on osx as g++4.8 is not yet available
  exclude:
    - os: osx
      compiler: gcc

before_install:
 # install
 - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
 - sudo apt-get update -qq
 - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-${GCC_VERSION}; fi
 - if [ "$CXX" = "g++" ]; then export CXX="g++-${GCC_VERSION}" CC="gcc-${GCC_VERSION}"; fi
 
 - wget http://sourceforge.net/projects/boost/files/boost/1.57.0/boost_1_57_0.tar.bz2/download -O /tmp/boost.tar.bz2
 - wget https://googlemock.googlecode.com/files/gmock-1.7.0.zip -O /tmp/gmock.zip
 - tar jxf /tmp/boost.tar.bz2
 - unzip /tmp/gmock.zip
 - mv boost_1_57_0 $PWD/third_party/boost
 - mv gmock-1.7.0 $PWD/third_party/gmock
 - export BOOST_ROOT="$PWD/third_party/boost"
 - cd $BOOST_ROOT
 - ./bootstrap.sh
 - ./b2 --with-thread --with-system -d0

 - cd $TRAVIS_BUILD_DIR
 - ls
 - if [ "$TRAVIS_OS_NAME" = "osx" ] && [ "$CC" = "gcc" ]; then export CC=gcc-4.8; fi
 - mkdir build

script:
 - cd build
 - cmake .. -DGPCXX_BUILD_DOCS=OFF
 - make 
 - make test

