git:
  depth: 200

language: cpp

compiler:
  - gcc
  - clang

os: 
  - linux
  - osx

env:
  global:
    - GCC_VERSION="4.9"
    - secure: "O6wBD6n4jqULZr92bdctOqXausjRbebOo2MNXODYYlQdzrmjwef3EzNOdObhQe8t8ivbVYph0RO1cl+Pjwhh1F/6qWQcRNS957ZsFmL3+0CVX9g1zZRa2Sz+FDoxQFi5MEpTkcjgZeGpX9VW7zjheIAtRRatTBj9pyxVptqne5o="
  matrix:
    - BUILD_TYPE=Debug
    - BUILD_TYPE=Release
    # - BUILD_TYPE=Coverage


matrix:
  # For now disable gcc on osx as g++4.8 is not yet available
  exclude:
    - os: osx
      compiler: gcc

before_install:
  - export GPCXX_ROOT=`pwd`
  
  # install g++
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-${GCC_VERSION}; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-${GCC_VERSION}" CC="gcc-${GCC_VERSION}"; fi

  # Install libc++ if tests are run with clang++
  # Taken from range-v3
  - if [ "$CXX" == "clang++" ]; then export LIBCXX=On; fi
  - if [ -n "$LIBCXX" -a "$CXX" == "clang++" ]; then svn co --quiet http://llvm.org/svn/llvm-project/libcxx/trunk libcxx; fi
  - if [ -n "$LIBCXX" -a "$CXX" == "clang++" ]; then cd libcxx/lib && bash buildit; fi
  - if [ -n "$LIBCXX" -a "$CXX" == "clang++" ]; then sudo cp ./libc++.so.1.0 /usr/lib/; fi
  - if [ -n "$LIBCXX" -a "$CXX" == "clang++" ]; then sudo mkdir /usr/include/c++/v1; fi
  - if [ -n "$LIBCXX" -a "$CXX" == "clang++" ]; then cd .. && sudo cp -r include/* /usr/include/c++/v1/; fi
  - if [ -n "$LIBCXX" -a "$CXX" == "clang++" ]; then cd /usr/lib && sudo ln -sf libc++.so.1.0 libc++.so; fi
  - if [ -n "$LIBCXX" -a "$CXX" == "clang++" ]; then sudo ln -sf libc++.so.1.0 libc++.so.1 && cd $cwd; fi

  # install valgrind
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get -qq install valgrind; fi
 
  # install third party dependencies
  - wget http://sourceforge.net/projects/boost/files/boost/1.57.0/boost_1_57_0.tar.bz2/download -O /tmp/boost.tar.bz2
  - wget https://googlemock.googlecode.com/files/gmock-1.7.0.zip -O /tmp/gmock.zip
  - tar jxf /tmp/boost.tar.bz2
  - unzip /tmp/gmock.zip
  - mv boost_1_57_0 $GPCXX_ROOT/third_party/boost
  - mv gmock-1.7.0 $GPCXX_ROOT/third_party/gmock
  - export BOOST_ROOT="$GPCXX_ROOT/third_party/boost"
  - cd $BOOST_ROOT
  - ./bootstrap.sh
  - ./b2 --with-thread --with-system -d0


install:
  # create build directory
  - cd $GPCXX_ROOT
  - mkdir build


script:
  - cd $GPCXX_ROOT
  - .ci/build_and_test.sh

after_success:
  - cd $GPCXX_ROOT
  - .ci/run_valgrind.sh





addons:
  coverity_scan:
    project:
      name: "Ambrosys/gpcxx"
      description: "Build submitted via Travis CI"
    notification_email: karsten.ahnert@gmx.de
    build_command_prepend: "cd build && cmake .. -DGPCXX_BUILD_DOCS=OFF"
    build_command:   "make"
    branch_pattern: coverity_scan