git:
  depth: 200

language: cpp

compiler:
  - gcc
  - clang

os: 
  - linux
  - osx

env:
  global:
    - GCC_VERSION="4.9"
    - RUN_VALGRIND=1
    # GIT_TOKEN
    - secure: "jq8/7MDVz6pZgu62Pfc+/MYlXoMQaSoOHITGZlS0JR71HM1zsMHyRtHbBtW2nuh2a82LmERuNH4iy4oeLJKO8sc6Wj3/glJhnefSd+KS03AEnPNPWfNZBC+GwxXoFaY0imE41CXtb2SzSzgzdh+uDBiPkgRXBzN4zzdV34OOpfc="
    # COVERITY_SCAN_TOKEN
    - secure: "KFTdHiHehYwK2SciIhdv3eDwi6nNWpwyjv8RqfiWs1ItFjr1292kLwKUVcjEz15tVQMmkWz8IbXe1YFMUbd8lswyRFO6Cpeaw9MP8yfnGkOxtdSddEtQyaujY8eiYQPkPjCGXg3uxzmhGdHx7OI4REcrjoWmKZvMXi/01CnXLnU="
    - REPO_PATH="https://headmyshoulder:${GIT_TOKEN}@github.com/Ambrosys/gpcxx.git"

  matrix:
    - BUILD_TYPE=Debug
    - BUILD_TYPE=Release

matrix:
  exclude:
    # For now disable gcc on osx as g++4.8 is not yet available
    - os: osx   
      compiler: gcc
    # Disable debug build of clang because of compiler errors with auto return types and debug informations
    - compiler: clang
      env: BUILD_TYPE=Release

    
    
before_install:
  - export GPCXX_ROOT=`pwd`
  - cd $GPCXX_ROOT
  - if [ "$CXX" == "g++" ] && [ "$BUILD_TYPE" == "Debug" ] && [ "$TRAVIS_BRANCH" == "master" ]; then export MASTER_BUILD=1; fi
  - if [ "$CXX" == "g++" ] && [ "$BUILD_TYPE" == "Debug" ]; then export COVERALLS_BUILD=1; fi
  - if [ -n "$MASTER_BUILD" ]; then echo "This is the Master build"; fi
  - if [ -n "$COVERALLS_BUILD" ]; then echo "This is the coverall build"; fi
  - if [ -n "$RUN_VALGRIND" ]; then echo "Running valgrind"; fi
  - .ci/setup_compiler.sh
  - .ci/init_thirdparty.sh
  # some variables need to be set here
  - export BOOST_ROOT="$GPCXX_ROOT/third_party/boost"




install:
  - cd $GPCXX_ROOT
  - mkdir build

script:
  - cd $GPCXX_ROOT
  - .ci/build_and_test.sh
  
after_success:
  - cd $GPCXX_ROOT
  - if [ -n "$MASTER_BUILD" ]; then .ci/commit_coverity_scan.sh; fi
  # - cd $GPCXX_ROOT
  # - if [ -n "$MASTER_BUILD" ]; then .ci/build_docs.sh; fi
  - cd $GPCXX_ROOT
  - if [ -n "$COVERALLS_BUILD" ]; then .ci/commit_coveralls.sh; fi 
