language: cpp

script: cmake

compiler:
  - gcc
  # - clang

os: 
  - linux
  - osx

env:
  global:
  - CXXSTD=''
  - CXXSTD='cxxflags="-std=c++11"'
  matrix:
    - BUILD_TYPE=Debug
    # - BUILD_TYPE=Release


matrix:
  # For now disable gcc on osx as g++4.8 is not yet available
  exclude:
    - os: osx
      compiler: gcc

before_install:
 - wget http://sourceforge.net/projects/boost/files/boost/1.57.0/boost_1_57_0.tar.bz2/download -O /tmp/boost.tar.bz2
 - wget https://googlemock.googlecode.com/files/gmock-1.7.0.zip -O /tmp/gmock.zip
 - tar jxf /tmp/boost.tar.bz2
 - mv boost_1_57_0 $PWD/boost
 - unzip /tmp/gmock.zip
 - mv gmock-1.7.0 $PWD/gmock
 - export BOOST_ROOT="$PWD/boost"
 - cd $PWD/boost
 - ./bootstrap.sh
 - ./b2 -with-thread -with-system

 - cd $TRAVIS_BUILD_DIR
 - ls
 - ls ..
 - if [ "$TRAVIS_OS_NAME" = "osx" ] && [ "$CC" = "gcc" ]; then export CC=gcc-4.8; fi
 - mkdir build

script:
 - cd third_party
 - ln -s $PWD/gmock .
 - ls
 - pwd
 - cd ../build
 - cmake .. -DGPCXX_BUILD_DOCS=OFF
 - make 
 - make test

