git:
  depth: 200

language: cpp

compiler:
  - gcc
  - clang

os: 
  - linux
  - osx

env:
  global:
    - GCC_VERSION="4.9"
    - secure: "O6wBD6n4jqULZr92bdctOqXausjRbebOo2MNXODYYlQdzrmjwef3EzNOdObhQe8t8ivbVYph0RO1cl+Pjwhh1F/6qWQcRNS957ZsFmL3+0CVX9g1zZRa2Sz+FDoxQFi5MEpTkcjgZeGpX9VW7zjheIAtRRatTBj9pyxVptqne5o="
  matrix:
    - BUILD_TYPE=Debug
    - BUILD_TYPE=Release

matrix:
  # For now disable gcc on osx as g++4.8 is not yet available
  exclude:
    - os: osx
      compiler: gcc
  include:
    # COVERITY
    # COVERALL
    # DOCS

    
    
before_install:
  - export GPCXX_ROOT=`pwd`
  - cd $GPCXX_ROOT
  - .ci/setup_compiler.sh
  - .ci/init_thirdparty.sh
  # some variables need to be set here
  - export BOOST_ROOT="$GPCXX_ROOT/third_party/boost"
  - if [ "$CXX" == "g++" ]; then export CXX="g++-${GCC_VERSION}" CC="gcc-${GCC_VERSION}"; fi

install:
  - cd $GPCXX_ROOT
  - mkdir build

script:
  - cd $GPCXX_ROOT
  - .ci/build_and_test.sh
  - .ci/run_valgrind.sh
  
after_success:
  - cd $GPCXX_ROOT
  # - if in master: build docs and push to gh-page
  # - if in master: push to coverity branch
  # coveralls




addons:
  coverity_scan:
    project:
      name: "Ambrosys/gpcxx"
      description: "Build submitted via Travis CI"
    notification_email: karsten.ahnert@gmx.de
    build_command_prepend: "cd build && cmake .. -DGPCXX_BUILD_DOCS=OFF"
    build_command:   "make"
    branch_pattern: coverity_scan